### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [tabatkins/railroad-diagrams#82]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary railroad-diagrams -w /tmp/ext railroad-diagrams==1.0.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting railroad-diagrams==1.0.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/342/d1b9e4bfc335d/railroad-diagrams-1.0.3.tar.gz (19 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-6_btpu_e/railroad-diagrams/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-6_btpu_e/railroad-diagrams/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-6_btpu_e/railroad-diagrams/pip-egg-info
         cwd: /tmp/pip-wheel-6_btpu_e/railroad-diagrams/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-6_btpu_e/railroad-diagrams/setup.py", line 3, in <module>
        with open("README-py.md", "r") as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'README-py.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by tabatkins** [comment]
fixed in #83
